services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bryzndb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # api-gateway:8081
  # movie-service:8082
  # notification-service:8083
  # payment-service:8084
  # seating-service:8085
  # user-management-service:8086
  # gui-service:8087
  # ticketing-manager:8088
  # service-orchestrator:8089
  # session-manager:8090
  
  user-management-service:
    image: ums
    container_name: user-management-service
    environment:
      SERVER_PORT: 8086
      
      # Spring
      SPRING_PROFILES_ACTIVE: test
      
      # Postgres 
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bryzndb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

      # CUSTOM
      SESSION_MANAGER: session-manager
      SESSION_MANAGER_PORT: 8090
      NOTIFICATION_SERVICE: notification-service
      NOTIFICATION_SERVICE_PORT: 8083

    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8086:8086"

  session-manager:
    image: sm
    container_name: session-manager
    environment:
        SERVER_PORT: 8090
        SPRING_CONFIG_LOCATION: file:/app/config/
        SPRING_PROFILES_ACTIVE: dev
    volumes:
    - ./config/application.properties:/app/config/application.properties
    ports:
      - "8090:8090"

  # payment-service:
  #   image: ps
  #   container_name: payment-service
  #   environment:
  #     SERVER_PORT: 8084
      
  #     # Spring
  #     SPRING_PROFILES_ACTIVE: test
      
  #     # Postgres 
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bryzndb
  #     SPRING_DATASOURCE_USERNAME: user
  #     SPRING_DATASOURCE_PASSWORD: password

  #     # CUSTOM
  #     SESSION_MANAGER: session-manager
  #     SESSION_MANAGER_PORT: 8090
  #     USER_MANAGEMENT_SERVICE: user-management-service
  #     USER_MANAGEMENT_SERVICE_PORT: 8086
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     - "8084:8084"
volumes:
  pgdata: